### ISSUE TITLE
Switch to sphinx documentation

### ISSUE THREAD

**Issue by capital-G** [strawberry-graphql/strawberry-django#207]
## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

I think the documentation is in danger of growing stale as it is detached from the code as it resides as markdown files in its own directory. Python allows via docstrings and Sphinx to tie the documentation to the code which every major python library is using and is from my experience maybe one of the best features of python. It also allows to automatically [run these code snippets for testing](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html), making sure that the docs are in a valid state.

I find it hard to understand the magic that happen behind the scenes of strawberry/strawberry-django and having not linked and auto-generated docs available makes it even harder to reconstruct what is happening.

E.g. the context of the `resolver` in <https://strawberry-graphql.github.io/strawberry-graphql-django/faq/> is unclear without further investigation as it is not linked to what a resolver is.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-graphql-django/issues/207">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/207/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-graphql-django/issues/207/pledge.svg">
</picture>
</a>

**Comment by thclark** [comment]
Hi, maintainer of rstcloth and sphinx-charts here (ie someone with overwhelming bias toward sphinx ecosystem).

I wouldn't do this.
1. The strawberry docs use mkdoc-material the same as django-strawberry, so if the future merge of this lib into strawberry does take place, it's best to have documentation in the same form to avoid a rewrite.
2. Even if that merge doesn't happen, a unified documentation system is hepplful since clearly a lot of maintainers overlap.
3. There are already a lot of issues here referring to how the docs are behind. Making the docs a lot harder for contributors to write (ReST is very awkward syntax compared to the near-universal markdown) will make this worse.
4. Wanting autodoc isn't a reason to switch to sphinx. If autodoc were required, [using autodoc with mkdoc is perfectly possible](https://github.com/tomchristie/mkautodoc).
  - IMO: Maybe many would disagree but I don't think autodoc will be of much value here. Since it seems like a lot of the functionality seems to rely on type inference, I think most of the internals of the library are best left untouched by users, and that the same setup effort elsewhere in documentation would yield more benefit.

**Comment by bellini666** [comment]
An update to this: Me and @patrick91 are working on integrating our current documentation into the official docs (https://strawberry.rocks/docs), the issue is being tracked in https://github.com/strawberry-graphql/strawberry.rocks/issues/492
