### ISSUE TITLE
optimizer and SimpleLazyObject

### ISSUE THREAD

**Issue by tasiotas** [strawberry-graphql/strawberry-django#579]
Hi,

I stumbled upon a case where user object from `info.context.request` isn't working with optimizer.

I have a query like this

```python
@strawberry.type
class Query:
    @strawberry_django.field
    def user(self, info, slug: Optional[str] = None) -> Optional[UserType]:
        if slug:
            user = User.objects.filter(slug=slug)
            return user
        else:
            user = info.context.request.user
            if user.is_authenticated:
                return user
            else:
                return None
```

and UserType
```python
@strawberry_django.type(User)
class UserType:
    @strawberry_django.connection(
        ListConnectionWithTotalCount[ProductRelayType], filters=ProductFilter, order=ProductOrder
    )
    def products(self) -> list["ProductRelayType"]:
        return self.products.all()
```

1. When I make a query like this, I get 2 DB queries, optimizer is working. All good 👍. Notice that when I specify `slug`, returned user is a qs, not an object.
```gql
query dashboardIndex {
  user(slug: "tas") {
    id
    products {
      edges {
        node {
          title
        }
      }
    }
  }
}
```

2. When I don't specify `slug`, but I am logged in, returned user is an SimpleLazyObject and I get 6 queries, not good 👎.
```gql
query dashboardIndex {
  user {
    id
    products {
      edges {
        node {
          title
        }
      }
    }
  }
}
```
3. If I return qs with user based on request's user pk, I get 3 DB queries. Optimizer is working, but I get one extra query, that seems unnecessary. 
```python
return User.objects.filter(pk=user.pk)
```

Am I doing something wrong or is all this expected behavior? 

Thank you

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/579">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/579/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/579/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
The reason this is happening is because:

1) For the `slug` case you are returning a `QuerySet`, and because of that the optimizer can intercept and optimize it

2) When you don't have a slug you are returning the user itself (which is lazily resolved using a `SimpleLazyObject`, but still =P), so the optimizer has no chance to actually optimize it.

---

One way to improve this is to change the else code to:

```python
            user = info.context.request.user
            if user.is_authenticated:
                return User.objects.filter(pk=user.pk)
            else:
                return None
```

This way you are going to return a queryset which is optimizable. This means you are going to query the user twice though, but it can be better than the extra 6 queries you are seeing.

A better way would be to actually get the user from the request already optimized, but it would require some very complex code to workaround that, and TBH I don't think it is worth it

Let me know if that answers your question, or if after that you can still spot any issue
