### ISSUE TITLE
Can't get single query working

### ISSUE THREAD

**Issue by gfort-amarena** [strawberry-graphql/strawberry-django#612]
Hello,

I have a feeling that this is a bug but i'd like another opinion to make sure i didn't miss something.

I currently am working on a django project on which I integrated strawberry_django to integrate GraphQL.

I have the following:

```
#note: Entity is the django model

@strawberry_django.order(Entity)
class EntityOrder:
    id: auto
    field_a: auto
    field_b: auto


@strawberry_django.filters.filter(Entity, lookups=True)
class EntityFilter:
    id: auto
    field_a: auto
    field_b: auto

@strawberry_django.type(Entity, fields="__all__", filters=EntityFilter, order=EntityOrder, pagination=True)
class EntityType:
    pass

@strawberry.type
class Query:
    entity: EntityType = strawberry_django.field()
    entities: list[EntityType] = strawberry_django.field()
```

When I look at Postman or the graphQL interface, I can see the filters properly on the query **entities**, but never on **entity**.

I tried to convert the query with something like this:
```
# resolver as a method
@strawberry.field()
def entity(self, _id: int) -> EntityType:
  return Entity.objects.get(pk=_id)
```

But I always get this error "You cannot call this from an async context - use a thread or sync_to_async." when I use the resolver method.

I am using **strawberry-graphql-django==0.47.1** and **strawberry-graphql==0.237.2**

Thanks for you help

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry-django/issues/612">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/612/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry-django/issues/612/pledge.svg">
</picture>
</a>

**Comment by bellini666** [comment]
Hey @gfort-amarena ,

This is expected! `entity: EntityType = strawberry_django.field()` is going to produce a resolver that returns an entity given its `ID`. There are no filters involved in this operation

The `entities: list[EntityType] = strawberry_django.field()` is the one that will add filters/ordering to your resolver.

> But I always get this error "You cannot call this from an async context - use a thread or sync_to_async." when I use the resolver method.

The issue there is that you used `@strawberry.field()` instead of `@strawberry_django.field()`. The reason you should use the second one is because it will make sure to wrap your resolver with [sync_to_async](https://docs.djangoproject.com/en/5.1/topics/async/#asgiref.sync.sync_to_async), ensuring it is properly resolved when running with ASGI.

---

As none of those are actually bugs, I'm going to close this issue. But if you feel that there's indeed a bug somewhere, let me know so I can reopen it.
